### ISSUE TITLE
Edge is not painting 

### ISSUE THREAD

**Issue by manhnguyen92** [hughplay/DFNet#10]
I have did some tests on Pre-trained model but the missing edges weren't fill. it's seem the edges is not be connected.

**Comment by hughplay** [comment]
Can you provide your example?

**Comment by manhnguyen92** [comment]
thank for your reply.
this is mask https://ibb.co/Sf21NhD
this is result https://ibb.co/x15zywN

the missing part of the line bar was not painting

**Comment by hughplay** [comment]
I'm afraid this is because the example you show is beyond DFNet's ability.

DFNet is a method of 2019. As for 2022, there are more advanced methods, such as [LAMA](https://github.com/saic-mdal/lama) and [LAION](https://github.com/CompVis/latent-diffusion). Have a try.

**Comment by manhnguyen92** [comment]
THANK so much
