### ISSUE TITLE
Can I just use DataLoader in Pytorch?

### ISSUE THREAD

**Issue by Lotayou** [hughplay/DFNet#3]
Hi! Thanks for your amazing work. I'm currently adapting your code to train on my own dataset, with slightly different data format. So I'm thinking about tweaking your data loading module a bit to suit my needs. However, your data loading module seems pretty convoluted, with multithreading and buffers, that I found hard to understand. 

I'm wondering, is your code functionally equivalent as `torch.data.utils.DataLoader`? Can I just implement my own Dataset object and use DataLoader for multi-thread reading? Will it be significantly slower than your implementation? Thanks!

**Comment by hughplay** [comment]
Of course you can.

Actually, the data loading code in `test.py` should be designed more carefully for better reading.
It's a little bit complex because I had some considerations for other functionalities.
