### ISSUE TITLE
something about training

### ISSUE THREAD

**Issue by ray0809** [hughplay/DFNet#6]
Hi Mr Blue,
 here I have some questions about training, Could you please give me some suggestions?
 
1. which layers are the perceptual and style loss used  (iin my opinion, the results of resolution with 256, 128, 64 if I trained celeba, is that right? the index in loss.py is [0,1,2])
2. the input of vgg is the results of model's output, is that right? 
4. in your loss.py the vgg feature extractor don't sub(mean) and div(std), why?
3. the reconstruction loss don't consider the hole and valid region (like Nvidia partialconv)

**Comment by hughplay** [comment]
Hi @ray0809 , these are my suggestions:

1. We use features just after first three pooling layer of VGG16. Please check the reference code:
https://github.com/hughplay/DFNet/blob/2b4abdecd29fe12effc4dfaac19955182f270649/loss.py#L39
1.  Yes. The inputs of VGG include model's output and target. And the results will be used to compute style loss and perceptual loss.
https://github.com/hughplay/DFNet/blob/2b4abdecd29fe12effc4dfaac19955182f270649/loss.py#L151
`r` represents `result`, `t` represents `target`
1. In our experiments, whether sub(mean) and div(std) have little influence. You can try yourself and compare the results.
1. same like 3.

Hope these suggestions are helpful.

**Comment by ray0809** [comment]
thanks for your reply~

**Comment by ray0809** [comment]
by the way, How long does training the celeba_hq dataset?
my experiment:
input_size: 256
batch_size: 74
epoch: 1000
celeba_hq: 3w for training 
one epoch : 405 iters
after traning one day(150 epoches), the results are blurry, similar with your paper said(only with reconstruction loss)
Do I need to continue training？

**Comment by hughplay** [comment]
It's hard to say.
In our experiments, models fit easily on CelebA that Places2. But overall, the training is quite computational expensive.
You can check Section 4.1 in my paper for some detail: http://arxiv.org/pdf/1904.08060.pdf

**Comment by ray0809** [comment]
ok, I will keep trying
Thanks ～
