### ISSUE TITLE
Output Result ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [hughplay/DFNet#9]
Hello, thank you for your amazing implementation,
I tried running the inference on custom images, the execution completed but the resulted images are not saved in the directory,
it'll be much appreciated if you would look into this issue
Thank you

**Comment by hughplay** [comment]
The results should be saved to the folder assigned by `--output`. Is that normal to run the example code?

```
python test.py --model model/model_places2.pth --img samples/places2/img --mask samples/places2/mask --output output/places2 --merge
```

**Comment by Adeel-Intizar** [comment]
I ran the command and it shows successful completion but all the 3 directories under output/places2 are empty
![image](https://user-images.githubusercontent.com/56041154/122176974-9c74ff80-ce9e-11eb-9b7d-bf18702e9248.png)

**Comment by Adeel-Intizar** [comment]
I tried running the samples provided in repo for places2 but it does nothing
![image](https://user-images.githubusercontent.com/56041154/122178739-4a34de00-cea0-11eb-9256-2f278eebaa46.png)

**Comment by hughplay** [comment]
checkout out this, it should work.

[<img src="https://colab.research.google.com/assets/colab-badge.svg">](https://colab.research.google.com/github/hughplay/DFNet/blob/master/demo.ipynb)

**Comment by Adeel-Intizar** [comment]
Thank you, I'll check it out
